sudo: required
language: python
python:
  - "2.7"
env:
  - LIBCROWDS_ANALYST_SETTINGS='../settings_test.py'
services:
  - redis-server
before_install:
  - sudo apt-get update
install:
  - pip install -U pip setuptools
  - pip install pep8 pytest pytest-cov mock coveralls
  - python setup.py install
script: 
  - python setup.py test
  - pep8
after_success:
  - coveralls
