ENDPOINT = 'http://example.com'
API_KEY = 'admin-api-key'
DOI = '123/456'
HOST = '0.0.0.0'
PORT = 5001
DEBUG = True
TESTING = True
THROTTLE = 0.01
MAIL_SERVER = 'localhost'
MAIL_PORT = 25
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_DEFAULT_SENDER = 'LibCrowds Analyst <analyst@libcrowds.com>'
MAIL_RECIPIENTS = ['test@example.com']
